apiVersion: v1
kind: Service
metadata:
  name: multiprobe
  annotations:
    booking.balancer.hostname: {{ .Values.service.annotations.balancer.hostname }}
    booking.balancer.hostpath: {{ .Values.service.annotations.balancer.hostpath }}
    booking.balancer.locality: "{{ .Values.service.annotations.balancer.locality }}"
    booking.balancer.scope: {{ .Values.service.annotations.balancer.scope }}
    booking.balancer.timeout: {{ .Values.service.annotations.balancer.timeout }}
  labels:
    app: {{ template "multiprobe.name" . }}
    chart: {{ template "multiprobe.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    shipper-lb: production
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "multiprobe.name" . }}
    shipper-lb: production
